apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-operator
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-operator-role
rules:
  - apiGroups: ["edge.example.com"]
    resources: ["edgedeployments", "edgedeployments/status"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list","watch","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edge-operator-role
subjects:
  - kind: ServiceAccount
    name: edge-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-agent-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list","watch","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-agent-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edge-agent-role
subjects:
  - kind: ServiceAccount
    name: edge-agent
    namespace: default

