apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edgedeployments.edge.example.com
spec:
  group: edge.example.com
  names:
    plural: edgedeployments
    singular: edgedeployment
    kind: EdgeDeployment
    shortNames:
      - ed
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
                maxLatencyMs:
                  type: integer
                minBandwidthMbps:
                  type: integer
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
              required: ["image"]
            status:
              type: object
              properties:
                phase:
                  type: string
                reason:
                  type: string
      subresources:
        status: {}

